### ISSUE TITLE
Format event fields in JSON

### ISSUE THREAD

**Issue by PowerSchill** [PowerSchill/minecraft-app#24]
Instead of using a KV string to specify fields we should use JSON so we can get a rich formatted event and enhanced support for multivalue fields.

**Comment by PowerSchill** [comment]
JSON formatting is not currently supported in HTTP Event Collector for actual event data.

**Comment by TheProducer835** [comment]
just to confirm here... statement above isn't completely accurate. HTTP Event Collector does support JSON as a payload.
