### ISSUE TITLE
No longer seeing tool value

### ISSUE THREAD

**Issue by TheProducer835** [PowerSchill/minecraft-app#7]
Tue Jun 14 10:57:12 PDT 2016 name=BlockEvent event_id= game_time=12029873 world=world x=-135 y=70 z=277 action=block_placed block_type=FIRE player=LordProducer008 base_type=FIRE tool_used= server=default

(should be (flint and steel)

Tue Jun 14 10:57:03 PDT 2016 name=BlockEvent event_id= game_time=12029693 world=world x=-135 y=72 z=279 action=block_placed block_type=OBSIDIAN player=LordProducer008 base_type=OBSIDIAN tool_used= server=default

(should be [was] tool=air

**Comment by PowerSchill** [comment]
I noticed that the action was block_placed. Where you actually placing the block or breaking it? If placing then I should remove the "tool_used" property from the log.

**Comment by TheProducer835** [comment]
perhaps... however, I just set an entire forest on fire and all I got was this:
Tue Jun 14 11:35:10 PDT 2016 name=BlockEvent event_id= game_time=12075413 world=world x=-248 y=65 z=236 action=block_placed block_type=FIRE player=LordProducer008 base_type=FIRE tool_used= server=default

In that case, the tool would be significant.
